spring:
  datasource:
    # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ???????
    url: jdbc:mysql://127.0.0.1:3306/report_form
    username: root
    password: 123456789
  mvc:
    static-path-pattern: classpath:/static/**
# mybatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml

# ???8081
server:
  port: 8081
